# Languages
#   Create a section for each of your site's languages.
#   Documentation: 

# Default language
en:
  languageCode: en-us
  #Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: Website
  params:
    description: This is a describtion...
  menu:
    main:
      - name: Menu
        url: '#about'
        weight: 2

# Uncomment the lines below to configure your website in a second language.
ru:
  languageCode: ru
  contentDir: content/ru
  title: Сайтик
  params:
    description: Это описание сайта, да
  menu:
    main:
      - name: Меню
        url: '#about'
        weight: 1
